config/routes.rb
Rails.application.routes.draw do
  

  get 'import/getdata', to: 'import#getdata'

  resources :weeks, except: [:new, :destroy, :update, :edit, :create]
  
  resources :users, except: [:new]
  
  resources :players, except: [:new, :destroy, :update, :edit, :create]
  
  get '/register', to: 'users#new'

  get '/importplayers', to: 'pages#importplayers'
  get '/importgames', to: 'pages#importgames'
  get '/importpicks', to: 'pages#importpicks'
  get '/importawards', to: 'pages#importawards'
  get '/logs', to: 'pages#showlogs'
  get '/summary', to: 'pages#summary'
  get '/updateawards', to: 'pages#updateawards'
  post '/nextwins', to: 'users#nextwins'
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  get 'updatecbs', to: "update#updatecbs"
  get '/bracket', to: "pages#brackettest"
  
  get '/updateawards/:id', to: 'pages#updateawards'

  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<% if logged_in? %>
  <%= link_to "Logout", logout_path, class: "button" %>
<% end %>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <% lastfullweek = get_lastfullweek %>
  <header>

    <% weeklist = get_weeks_list %>
    <ul>
      <li><%= link_to "Summary", summary_path %></li>
      <li class="dropdown">
        <a href="javascript:void(0)" class="dropbtn" onclick="myFunction()">Weekly Results</a>
        <div class="dropdown-content" id="myDropdown">
          <%= raw weeklist %>
        </div>
      </li>
      <% if @current_user != nil && @current_user.username == "tbowl" %>
        <li><%= link_to "Create Profile", register_path %></li>
      <% end %>
      <% if @current_user != nil && @current_user.username != "tbowl" %>
        <li><%= link_to "Edit Profile", edit_user_path(@current_user) %></li>
      <% end %>
      <% if @current_user != nil && @current_user.username != "tbowl" && lastfullweek > 0 %>
        <% teampage =Player.find_by_cbsid(@current_user.cbs_id).playername + " Team Page" %>
        <li><%= link_to teampage, user_path(@current_user) %></li>
      <% end %>
      <li><%= link_to "Logout", logout_path %></li>
      <% if @current_user != nil && @current_user.username == "c51999" %>
        <li><%= link_to "Update", import_getdata_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Logs", logs_path %></li>
      <% end %>
    </ul>

  </header>

  <h1 class="title">Toilet Bowl 2019 - 2020</h1>
  <hr>
  
<script type="text/javascript">
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(e) {
  if (!e.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    for (var d = 0; d < dropdowns.length; d++) {
      var openDropdown = dropdowns[d];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

<% else %>
  <header>
    
    <div class="logonheader">&nbsp</div>
  </header>
  <h1 class="title">Toilet Bowl 2019 - 2020</h1>
  <hr>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-133288460-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-133288460-1');
    </script>

  <title>TBowl 2019 - 2020</title>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>

<%= yield %>


</body>
</html>